@backend_HostAddress = http://localhost:8080

POST {{backend_HostAddress}}/api/linkedin/auth/login
Content-Type: application/json

{
	"provider": "linkedin",
	"username": "your-linkedin-user",
	"password": "your-linkedin-password"
}

###

GET {{backend_HostAddress}}/api/linkedin/auth/status
Accept: application/json

###

POST {{backend_HostAddress}}/api/linkedin/search/scrape
Content-Type: application/json

{
	"query": ".NET",
	"location": "Remote",
	"limit": 10,
	"providers": ["linkedin", "indeed"]
}

###

GET {{backend_HostAddress}}/api/linkedin/jobs
Accept: application/json

###

GET {{backend_HostAddress}}/api/jobs/jobs
Accept: application/json

###

GET {{backend_HostAddress}}/api/jobs/leads?minScore=60&directOnly=true
Accept: application/json

###

GET {{backend_HostAddress}}/api/jobs/leads/filter?minScore=60&directOnly=true&category=Backend&companyType=DirectClient&search=.net
Accept: application/json

###

GET {{backend_HostAddress}}/api/jobs/processed
Accept: application/json

###

GET {{backend_HostAddress}}/api/jobs/unprocessed
Accept: application/json

###

POST {{backend_HostAddress}}/api/jobs/process
Accept: application/json

