namespace backend.Domain.Entities;

/// <summary>
/// A commercial cluster of JobInsights grouped by (PainCategory + TechTop3 + Industry + CompanyType).
/// Produced by the ClusterEngine (Worker 2), evaluated by the DecisionEngine (Worker 4),
/// and synthesized by ClusterSynthesisService via LLM (Worker 3 / Fase 3).
/// </summary>
public class MarketCluster
{
    public int Id { get; set; }

    // --- Cluster identity ---

    /// <summary>
    /// Deterministic key: SHA256(PainCategory|TechTop3|Industry|CompanyType).
    /// Used for upsert — same cluster across rebuilds produces the same key.
    /// </summary>
    public string ClusterKey { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable label generated by the engine.
    /// Example: "Fintechs migrando NET a Azure (DirectClient)"
    /// </summary>
    public string Label { get; set; } = string.Empty;

    public string PainCategory { get; set; } = string.Empty;

    /// <summary>Canonical tech tokens sorted and joined: "AZURE, NET, SQL"</summary>
    public string NormalizedTechStack { get; set; } = string.Empty;

    /// <summary>Top 3 canonical tokens joined by pipe for the key: "AZURE|NET|SQL"</summary>
    public string TechKeyPart { get; set; } = string.Empty;

    public string Industry { get; set; } = "Unknown";

    /// <summary>DirectClient | Consulting | Mixed</summary>
    public string CompanyType { get; set; } = string.Empty;

    // --- Market signals ---

    public int JobCount { get; set; }
    public int DirectClientCount { get; set; }
    public double DirectClientRatio { get; set; }
    public double AvgOpportunityScore { get; set; }
    public double AvgUrgencyScore { get; set; }

    /// <summary>
    /// Percentage growth of jobs in this cluster vs. the previous 7-day window.
    /// Positive = growing demand. Negative = declining.
    /// </summary>
    public double GrowthRate { get; set; }

    // --- Scoring components (stored for transparency / debugging) ---

    /// <summary>0–100. Weight by industry: Fintech=100, Health=90, Ecommerce=85, Logistics=80, Unknown=50.</summary>
    public double BuyingPowerScore { get; set; }

    /// <summary>40 for General category, 100 for specific categories.</summary>
    public double PainSpecificityScore { get; set; }

    /// <summary>(DirectClientRatio*70) + (AvgUrgency/10*30). Max 100.</summary>
    public double EaseOfSaleScore { get; set; }

    /// <summary>
    /// Composite BlueOceanScore v2 (0–100).
    /// = volume*0.30 + growth*0.20 + directRatio*0.20 + urgency*0.10 + buyingPower*0.10 + easeOfSale*0.10
    /// </summary>
    public double BlueOceanScore { get; set; }

    /// <summary>1 = highest BlueOceanScore. Updated on every rebuild.</summary>
    public int RoiRank { get; set; }

    // --- Decision Engine output (Fase 6) ---

    /// <summary>MVPProduct | QuickWin | Consulting | Ignore</summary>
    public string OpportunityType { get; set; } = "Ignore";

    /// <summary>True when BlueOceanScore >= 50 AND OpportunityType != Ignore.</summary>
    public bool IsActionable { get; set; }

    /// <summary>
    /// Commercial strategy assigned by the Decision Engine.
    /// Example: "Build MVP + Validate + Ads", "Direct Outreach (manual)"
    /// </summary>
    public string RecommendedStrategy { get; set; } = string.Empty;

    /// <summary>
    /// Ranking score 0–100 for executive prioritization.
    /// = BlueOcean*0.50 + directRatio*0.20 + urgency*0.20 + growth*0.10
    /// </summary>
    public int PriorityScore { get; set; }

    // --- LLM synthesis (Fase 3) ---

    public string? SynthesizedPain { get; set; }
    public string? SynthesizedMvp { get; set; }
    public string? SynthesizedLeadMessage { get; set; }

    /// <summary>MVPProduct | QuickWin | Consulting — from LLM response</summary>
    public string? MvpType { get; set; }

    public int? EstimatedBuildDays { get; set; }
    public decimal? EstimatedDealSizeUsd { get; set; }

    /// <summary>pending | done | needs_review | skipped</summary>
    public string LlmStatus { get; set; } = "pending";

    // --- Metadata ---

    public DateTime FirstSeenAt { get; set; }
    public DateTime LastUpdatedAt { get; set; }

    /// <summary>Engine version that produced this cluster (e.g. "cluster-v1").</summary>
    public string EngineVersion { get; set; } = "cluster-v1";

    // Navigation
    public ICollection<JobInsight> Insights { get; set; } = [];
}
