namespace backend.Domain.Entities;

/// <summary>
/// A consolidated, sellable product generated by aggregating multiple actionable MarketClusters
/// that share the same ProductCatalog entry (same ProductName).
/// One row per unique product name — clusters are referenced via ClusterIdsJson.
/// </summary>
public class ProductSuggestion
{
    public int Id { get; set; }

    /// <summary>
    /// Unique product name (catalog entry). Acts as the natural key for upsert.
    /// Example: ".NET Azure Migration Sprint"
    /// </summary>
    public string ProductName { get; set; } = string.Empty;

    /// <summary>
    /// JSON array of cluster IDs that contributed to this consolidated product.
    /// Example: "[3, 7, 12]"
    /// </summary>
    public string ClusterIdsJson { get; set; } = "[]";

    /// <summary>1–2 sentence description of what is being sold.</summary>
    public string ProductDescription { get; set; } = string.Empty;

    /// <summary>
    /// Aggregated market signal summary (sum of jobs, avg direct ratio).
    /// Example: "47 empresas · 88% directo · urgencia 7.2/10"
    /// </summary>
    public string WhyNow { get; set; } = string.Empty;

    /// <summary>Offer with price and timeline. Example: "Sprint de 14 días · $11,500"</summary>
    public string Offer { get; set; } = string.Empty;

    /// <summary>Single action to execute today.</summary>
    public string ActionToday { get; set; } = string.Empty;

    /// <summary>
    /// Distinct tech tokens across all contributing clusters, joined with " + ".
    /// Example: "NET + AZURE + SQL + DOCKER"
    /// </summary>
    public string TechFocus { get; set; } = string.Empty;

    /// <summary>Estimated delivery days from the catalog entry.</summary>
    public int EstimatedBuildDays { get; set; }

    /// <summary>Minimum deal size in USD.</summary>
    public decimal MinDealSizeUsd { get; set; }

    /// <summary>Maximum deal size in USD.</summary>
    public decimal MaxDealSizeUsd { get; set; }

    // ── Aggregated metrics ────────────────────────────────────────────────────

    /// <summary>Sum of JobCount across all contributing clusters.</summary>
    public int TotalJobCount { get; set; }

    /// <summary>Weighted average of DirectClientRatio across contributing clusters.</summary>
    public double AvgDirectClientRatio { get; set; }

    /// <summary>Weighted average of AvgUrgencyScore across contributing clusters.</summary>
    public double AvgUrgencyScore { get; set; }

    /// <summary>Max BlueOceanScore among contributing clusters.</summary>
    public double TopBlueOceanScore { get; set; }

    /// <summary>Sum of contributing clusters.</summary>
    public int ClusterCount { get; set; }

    /// <summary>
    /// Dominant OpportunityType among contributing clusters (MVPProduct | QuickWin | Consulting).
    /// </summary>
    public string OpportunityType { get; set; } = string.Empty;

    /// <summary>
    /// Primary industry among contributing clusters (most common, or "Multiple" if mixed).
    /// </summary>
    public string Industry { get; set; } = "Unknown";

    /// <summary>Max PriorityScore among contributing clusters — used for ordering.</summary>
    public int PriorityScore { get; set; }

    // ── LLM tactical synthesis (Tarea 2) ─────────────────────────────────────

    /// <summary>
    /// JSON object with tactical implementation plan generated by LLM.
    /// Schema: { implementacion, requerimientos, tiempo_y_tecnologias, empresas_objetivo }
    /// Null until user triggers "Generar Plan de Ataque (IA)".
    /// </summary>
    public string? SynthesisDetailJson { get; set; }

    /// <summary>pending | completed | failed</summary>
    public string LlmStatus { get; set; } = "pending";

    /// <summary>When this consolidated product was last generated/updated.</summary>
    public DateTime GeneratedAt { get; set; }
}
